apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awslab-app
  namespace: argocd
  annotations:
  argocd-image-updater.argoproj.io/image-list: | 
    aws-lab=653082655171.dkr.ecr.eu-north-1.amazonaws.com/aws-lab
 
spec:
  project: default
  source:
    repoURL: https://github.com/shimon23/AWSLab.git   
    targetRevision: master
    path: AWSLab-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
