apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awslab-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YourUser/AWSLab.git   
    targetRevision: main
    path: AWSLab-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
