replicaCount: 2

image:
  repository: 653082655171.dkr.ecr.eu-north-1.amazonaws.com/aws-lab
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: "adc6eaf21f7f244d9bf3c18dae65f5ee-1322497915.eu-north-1.elb.amazonaws.com"
      paths:
        - path: /
          pathType: Prefix
