replicaCount: 2

image:
  repository: 653082655171.dkr.ecr.eu-north-1.amazonaws.com/aws-lab
  pullPolicy: IfNotPresent
  tag: "v1.3.0"


service:
  type: ClusterIP
  port: 80

db:
  host: "awslab-db.cv82aa4w6eha.eu-north-1.rds.amazonaws.com"
  port: 3306
  name: awslabdb
  secretName: awslab-db-credentials

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: "adc6eaf21f7f244d9bf3c18dae65f5ee-1322497915.eu-north-1.elb.amazonaws.com"
      paths:
        - path: /
          pathType: Prefix
