apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awslab.fullname" . }}
  labels:
    {{- include "awslab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "awslab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "awslab.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: awslab
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
